name = "HyperbolicCrossApprox"
uuid = "db4fe9aa-a353-4142-ac3f-608941c5a4fc"
authors = ["RJDennis <richard.dennis@glasgow.ac.uk>"]
version = "0.3.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ChebyshevApprox = "17a596ad-87cd-578c-9b6d-01108c31dc04"
SmolyakApprox = "6b19cf85-48de-5d9d-bfff-465abea14fab"

[compat]
julia = "^1.6"
ChebyshevApprox = "^0.4"
SmolyakApprox = "^0.3"
