name = "HyperbolicCrossApprox"
uuid = "db4fe9aa-a353-4142-ac3f-608941c5a4fc"
authors = ["RJDennis <richard.dennis@glasgow.ac.uk>"]
version = "0.1.1"

[deps]
ChebyshevApprox = "17a596ad-87cd-578c-9b6d-01108c31dc04"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
SmolyakApprox = "6b19cf85-48de-5d9d-bfff-465abea14fab"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[compat]
julia = "^1.3"
ThreadPools = "^2.0"
ChebyshevApprox = "^0.1.13"
SmolyakApprox = "^0.1.8"
FLoops = "0.1.11"
Combinatorics = "1.0.2"