name = "HyperbolicCrossApprox"
uuid = "db4fe9aa-a353-4142-ac3f-608941c5a4fc"
authors = ["RJDennis <richard.dennis@glasgow.ac.uk>"]
version = "0.3.0"

[deps]
ChebyshevApprox = "17a596ad-87cd-578c-9b6d-01108c31dc04"
SmolyakApprox = "6b19cf85-48de-5d9d-bfff-465abea14fab"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"

[compat]
julia = "^1.6"
ThreadPools = "^2.0"
ChebyshevApprox = "^0.3"
SmolyakApprox = ">=0.2.2"
